version: '3'

networks:
  frontend-local:
    driver: bridge

services:
  proxy:
    build:
      context: ../../../proxy
      dockerfile: .deploy/local.Dockerfile
      args:
        CONFIG_FILE: frontend/frontend.local.conf
    image: proxy-local
    container_name: proxy-local
    ports:
      - '${PROXY_PORT:-80}:80'
    environment:
      NGINX_SERVER: ${NGINX_SERVER:-localhost}
      FRONTEND_PORT: ${FRONTEND_PORT:-5173}
    depends_on:
      - frontend
    volumes:
      - ../../../proxy/frontend/frontend.local.conf:/etc/nginx/templates/default.conf.template
    networks:
      - frontend-local

  frontend:
    build:
      context: ../..
      dockerfile: .deploy/local/Dockerfile
      args:
        FRONTEND_PORT: ${FRONTEND_PORT:-5173}
    entrypoint:
      [
        '/bin/sh',
        '-c',
        'npm install --force --silent && npm run dev -- --host --port ${FRONTEND_PORT:-5173}'
      ]
    image: frontend-local
    container_name: frontend-local
    environment:
      PORT: ${FRONTEND_PORT:-5173}
      VITE_API_URL: ${VITE_API_URL:-https://contractis.ru/api}
      VITE_SOCKET_HOST: ${VITE_SOCKET_HOST:-wss://contractis.ru/}
      VITE_GOOGLE_MAP_TOKEN: ${VITE_GOOGLE_MAP_TOKEN}
    restart: unless-stopped
    ports:
      - ${FRONTEND_PORT:-5173}:${FRONTEND_PORT:-5173}
    volumes:
      - ../..:/app
    networks:
      - frontend-local
